remote_theme: just-the-docs/just-the-docs
description: "Guidance and best practices for developing Thunderbird extensions."
baseurl: "/webext-support"
title: "Thunderbird WebExtension Coding Strategies"
logo: "/assets/logo.png"  # path relative to /docs
logo_only: true  # display only the logo in the sidebar header

url: "https://thunderbird.github.io/webext-support"
color_scheme: light

# Navigation
nav_external_links:
  - title: "Add-on Developer Guide"
    url: "https://developer.thunderbird.net/add-ons/about-add-ons"
  - title: "WebExtension API Documentation"
    url: "https://webextension-api.thunderbird.net/en/mv3/"
  - title: "Return to the webext-support GitHub repository"
    url: "https://github.com/thunderbird/webext-support"

# Define look of right-side TOC
just_the_docs:
  search_enabled: true
  show_toc: true
  toc_label: "On this page"
