remote_theme: just-the-docs/just-the-docs
description: "Guidance and best practices for developing Thunderbird extensions."
baseurl: "/webext-support"
title: "Thunderbird WebExtension Coding Strategies"
logo: "https://thunderbird.github.io/webext-support/assets/logo.png"
logo_only: true

url: "https://thunderbird.github.io/webext-support"
color_scheme: light

# Navigation
nav_external_links:
  - title: "Return to the webext-support GitHub repository"
    url: "https://github.com/thunderbird/webext-support"

# Define look of right-side TOC
just_the_docs:
  search_enabled: true
  show_toc: true
  toc_label: "On this page"
