remote_theme: just-the-docs/just-the-docs
baseurl: "/webext-support"
title: "Coding Strategies for Add-on Developers"
logo: "/assets/logo.png"
logo_only: true

url: "https://thunderbird.github.io/webext-support"
color_scheme: light

include:
  - assets

# Navigation
nav_external_links:
  - title: "Return to the webext-support GitHub repository"
    url: "https://github.com/thunderbird/webext-support"

# Define look of right-side TOC
just_the_docs:
  search_enabled: true
